# Generated by Django 5.2.4 on 2025-07-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20250716_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='collection',
            field=models.IntegerField(),
        ),
    ]
