# Generated by Django 5.2.4 on 2025-07-17 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_product_collection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='collection',
            new_name='collection_id',
        ),
    ]
