# Generated by Django 5.2.4 on 2025-07-17 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_collection_product_collection_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='collection_id',
        ),
        migrations.AddField(
            model_name='product',
            name='collection',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.PROTECT, to='store.collection'),
            preserve_default=False,
        ),
    ]
