# Generated by Django 5.2.4 on 2025-07-17 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_product_collection_id_product_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='collection',
            field=models.ForeignKey(default=20, on_delete=django.db.models.deletion.PROTECT, to='store.collection'),
        ),
    ]
